### ISSUE TITLE
CupertinoTheme based on Device Brightness?

### ISSUE THREAD

**Issue by JonasJW** [stryder-dev/flutter_platform_widgets#120]
Is there a way to display light/dark mode based on the Devices brightness in iOS? I tried this:

    void main() => runApp(MyApp());

    class MyApp extends StatelessWidget {

      @override
      Widget build(BuildContext context) {

        final materialLightTheme = ThemeData(
          primaryColor: Colors.blueAccent,
          brightness: Brightness.light,
          scaffoldBackgroundColor: MyColors.backgroundColor0(Brightness.light),
          appBarTheme: AppBarTheme(
            color: MyColors.backgroundColor1(Brightness.light)
          ),
        );

        final materialDarkTheme = ThemeData(
          primaryColor: Colors.blueAccent,
          brightness: Brightness.dark,
          scaffoldBackgroundColor: MyColors.backgroundColor0(Brightness.dark),
          appBarTheme: AppBarTheme(
            color: MyColors.backgroundColor1(Brightness.dark)
          ),
        );

        final cupertinoTheme = new CupertinoThemeData(
          primaryColor: Colors.blueAccent,
          scaffoldBackgroundColor: MyColors.backgroundColor0(Brightness.light),
          barBackgroundColor: MyColors.backgroundColor1(Brightness.light)
        );

        final cupertinoThemeDark = new CupertinoThemeData(
          primaryColor: Colors.blueAccent,
          scaffoldBackgroundColor: MyColors.backgroundColor0(Brightness.dark),
          barBackgroundColor: MyColors.backgroundColor1(Brightness.dark)
        );

        Brightness brightness = MediaQuery.of(context).platformBrightness;

        return PlatformProvider(
          builder: (context) => PlatformApp(
            title: "Cali Move App",
            android: (context) {
              return MaterialAppData(
                darkTheme: materialDarkTheme,
                theme: materialDarkTheme,
                // themeMode: brightness == Brightness.light
                //   ? ThemeMode.light
                //   : ThemeMode.dark
              );
            },
            ios: (context) {
              return new CupertinoAppData(
                theme: brightness == Brightness.light
                    ? cupertinoTheme
                    : cupertinoThemeDark,
                // home: MyHomePage(),
              );
            } 
          ),
        );
      }
    }

But I can't query the brightess with `MediaQuery` in the build method because `MediaQuery.of() called with a context that does not contain a MediaQuery `.

**Comment by JonasJW** [comment]
A possible workaround is to wrap the PlatformProvider with an `MaterialApp` like this: `void main() => runApp(MaterialApp(home: MyApp()));`

**Comment by aqwert** [comment]
Just a hunch, could you get the brightness within the context of setting the theme

```
return PlatformProvider(
      builder: (context) => PlatformApp(
        title: "Cali Move App",
        android: (context) {
          return MaterialAppData(
            darkTheme: materialDarkTheme,
            theme: materialDarkTheme,
            // themeMode: brightness == Brightness.light
            //   ? ThemeMode.light
            //   : ThemeMode.dark
          );
        },
        ios: (context) {
          Brightness brightness = MediaQuery.of(context).platformBrightness;
          return new CupertinoAppData(
            theme: brightness == Brightness.light
                ? cupertinoTheme
                : cupertinoThemeDark,
            // home: MyHomePage(),
          );
        } 
      ),
    );
```

**Comment by JonasJW** [comment]
I thought that too but it doesn't seem to work. I get the same error this way.

**Comment by aqwert** [comment]
That leaves the question of how to do this with just `CupertinoApp` itself since the theme property is set before the `CupertinoApp` is built.

**Comment by aqwert** [comment]
There is `CupertinoTheme.brightnessOf(context)` that may work. The code it has is

```
  static Brightness brightnessOf(BuildContext context, { bool nullOk = false }) {
    final _InheritedCupertinoTheme inheritedTheme = context.dependOnInheritedWidgetOfExactType<_InheritedCupertinoTheme>();
    return inheritedTheme?.theme?.data?._brightness ?? MediaQuery.of(context, nullOk: nullOk)?.platformBrightness;
  }
```
ref: https://github.com/flutter/flutter/blob/ef62092b9b8b1c92de9f16108814c0a3b34cb59d/packages/flutter/lib/src/cupertino/theme.dart#L82

**Comment by aqwert** [comment]
Though it again may be an issue because of the way the `CupertinoApp` is built..

```
Widget build(BuildContext context) {
    final CupertinoThemeData effectiveThemeData = widget.theme ?? const CupertinoThemeData();

    return ScrollConfiguration(
      behavior: _AlwaysCupertinoScrollBehavior(),
      child: CupertinoUserInterfaceLevel(
        data: CupertinoUserInterfaceLevelData.base,
        child: CupertinoTheme(
          data: effectiveThemeData,
          child: Builder(
            builder: (BuildContext context) {
              return WidgetsApp(

```
ref: https://github.com/flutter/flutter/blob/ef62092b9b8b1c92de9f16108814c0a3b34cb59d/packages/flutter/lib/src/cupertino/app.dart#L330

**Comment by aqwert** [comment]
Some flutter related issues: 

https://github.com/flutter/flutter/issues/42089
https://github.com/flutter/flutter/issues/42473
https://github.com/flutter/flutter/issues/33873

**Comment by aqwert** [comment]
Option B could be making a something like... (Just a thought experiment.)

```
return PlatformThemeProvider(
   child: PlatformProvider(
        androidThemes: MaterialThemingData(light: materialLightTheme, dark: materialDarkTheme),
        iosThemes: CupertinoThemingData(light: cupertinoTheme, dark: cupertinoThemeDark)
        builder: (context) => PlatformApp(
```

Then perhaps for each `PlatformScaffold` build it checks the brightness (`Brightness brightness = MediaQuery.of(context).platformBrightness;`) and then instructs the PlatformProvider to use the dark or light theme for the platform  if it is different.

The PlatformApp then can get the Theme (dark or light) from the `PlatformThemeProvider` as it rebuilds, which will return either the dark or light theme.

This would also eliminate the need to set the light or dark theme on the MaterialApp and the theme on the CupertinoApp using the MaterialAppData or CupertinoAppData objects.

**Comment by aqwert** [comment]
## Most probably solution

Use **`CupertinoDynamicColor`**

```
final cupertinoTheme = new CupertinoThemeData(
      primaryColor: CupertinoDynamicColor.withBrightness(
             color: Colors.blueAccent, 
             darkcolor: Colors.blueAccent,
      ),
      scaffoldBackgroundColor: CupertinoDynamicColor.withBrightness(
            color: MyColors.backgroundColor0(Brightness.light),
            darkColor: MyColors.backgroundColor0(Brightness.dark),
      )  
      barBackgroundColor: CupertinoDynamicColor.withBrightness(
            color: MyColors.backgroundColor1(Brightness.light),
            darkColor: MyColors.backgroundColor1(Brightness.dark),
      )  
    );

return PlatformProvider(
      builder: (context) => PlatformApp(
        title: "Cali Move App",
        ios: (context) {
          return new CupertinoAppData(
            theme: cupertinoTheme
          );
        } 
      ),
    );
```

This should/will pick the light or dark themes correctly.

https://github.com/flutter/flutter/blob/5df63738f8ca865c1f1ed03e76bd504e9c9bfd73/packages/flutter/lib/src/cupertino/colors.dart#L888

https://github.com/flutter/flutter/blob/ba7176416f79fedb87d4bb8f2693ec1e7f2d45d1/packages/flutter/lib/src/cupertino/colors.dart#L946

**Comment by aqwert** [comment]
Can you confirm whether the above suggestion resolves the issue?

**Comment by JonasJW** [comment]
Sorry I didn't reply earlier. That solution works aswell. 

Is there any problem with wrapping the Platform App in a MaterialApp as I descibed earlier tough? It seems to work quite well for me and that way I can use `MediaQuery.of(context).platformBrightness` to get the brightness when building the `CupertinoApp`. This fits my needs better because I can use the same `getColor` Methods across the whole app, which return colors based on the brightness.

**Comment by aqwert** [comment]
If it works then it is ok. I am not sure about what side effects can occur by doing that.

**Comment by Valentin-Seehausen** [comment]
It actually does not really set the text color in dark mode. Could that be?

**Comment by Valentin-Seehausen** [comment]
Ah you can also listen to the system brightness and set is as state in your AppState:

```
class _AppState extends State<App> with WidgetsBindingObserver {
  Brightness _brightness = WidgetsBinding.instance.window.platformBrightness;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangePlatformBrightness() {
    setState(() {
      _brightness = WidgetsBinding.instance.window.platformBrightness;
    });
  }

  ...

    return Theme(
      data: _brightness == Brightness.light ? materialTheme : materialDarkTheme,
      
...
```

**Comment by aqwert** [comment]
Closing as any issues around this is related to flutter itself and not this library
