### ISSUE TITLE
Provider Package

### ISSUE THREAD

**Issue by alanmeier** [stryder-dev/flutter_platform_widgets#132]
Hi there,

Was looking at using the package in my app, what you have done looks great. 

Will there be support for the provider model in future ?

I am new to flutter but best practice was not to make the root app stateful as platform_widgets does. 

Thanks
Alan

**Comment by aqwert** [comment]
Perhaps not using Provider directly but I have been thinking of improving the PlatformProvider, one of which to make it stateless

**Comment by StevenKek** [comment]
I'm not sure I follow. Provider package has nothing to do with flutter_platform_widgets, right?
I mean... does it work worse with flutter_platform_widgets compared to vanilla widgets?
