### ISSUE TITLE
PlatformAppBar

### ISSUE THREAD

**Issue by alanmeier** [stryder-dev/flutter_platform_widgets#134]
Hi there,

Thanks for the library

Found a minor issue where if you initialise the bar as follows
      appBar: PlatformAppBar(
        title: Text('Message'),
        backgroundColor: Colors.black,
        ios: (_) => CupertinoNavigationBarData(
              transitionBetweenRoutes: true,
            ),
      ),

On an Android device the text is in white and is displayed on IOS the text is still black and is not displayed.

Thanks
Alan

**Comment by fredgrott** [comment]
Hello Alan,

Take a look at the example main.dart file. From what I gather from your code snippet you should switch some stuff to doing specific themes, ie CupertinoLightDark and Material as I am assuming that background color will be on of the ones that gets switched via the platform provider widget.

Can you post more of your code and I will check back on Tues or Wed to see if I can spot the correction needed?

**Comment by alanmeier** [comment]
Hi there,

I thought that when you set the background colors on creation it should work. The background colorats does not seem to work properly as a property as when I say use black for the AppBar on Android it stays purple and I am using the latest versio
[Globals.txt](https://github.com/aqwert/flutter_platform_widgets/files/4119276/Globals.txt)
n. I have attached the source and Yaml for you to see and comment as txt files.

I was trying to use it as plain vanilla as possible so that I could avoid constantly using branding by OS which I thought kind of defeated the purpose of using platform widgets.

Thanks
[main.txt](https://github.com/aqwert/flutter_platform_widgets/files/4119266/main.txt)
[settings_screen.txt](https://github.com/aqwert/flutter_platform_widgets/files/4119270/settings_screen.txt)
[pubspec.txt](https://github.com/aqwert/flutter_platform_widgets/files/4119273/pubspec.txt)




<img width="839" alt="Screen Shot" src="https://user-images.githubusercontent.com/19872571/73212234-a9faee00-41b2-11ea-91c1-3603641d203e.png">

**Comment by fredgrott** [comment]
Looks like, similar to one of my problems 

I am thinking we both need to do:


CupertinoBottomNavBarTheme

offhand  my main thing is I was doing some advance stuff with the code example to show some very advance stuff for this plugin and why to use that adv stuff to improve the docs  

I hope it helps

**Comment by aqwert** [comment]
Closing as this is a flutter issue
