### ISSUE TITLE
Add Platform_date_picker

### ISSUE THREAD

**Issue by nateshmbhat** [stryder-dev/flutter_platform_widgets#143]
add cupertino and material date picker

**Comment by fredgrott** [comment]
material date picker is here in the api
https://api.flutter.dev/flutter/material/showDatePicker.html

and the cupertino one is here
https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html

Does that answer your use cases?

**Comment by shock-wave007** [comment]
https://github.com/shock-wave007/Flutter-platfrom-aware-other-widgits

try this for mean time for basic i made this package with help of this library

**Comment by martin-braun** [comment]
@aqwert Great out of the box solution, but sadly too limited, because you can only pick days, not a time.
