### ISSUE TITLE
Support for PopupMenuButton and CupertinoActionSheet

### ISSUE THREAD

**Issue by ekuleshov** [stryder-dev/flutter_platform_widgets#148]
Flutter's PopupMenuButton widget has an itemBuilder with list of PopupMenuItem widgets.

It would be really handy to be able to replace these menu item widgets on ios with CupertinoActionSheetAction widgets and use CupertinoActionSheet to show them instead of Android's default popup menu.

**Comment by aqwert** [comment]
Certainly something I am thinking about. I personal project does this to some extent though would need to be cleaned up. Question is whether the Material menu popup and the Cupertino action sheet is the expected equivalent to eachother.

**Comment by aqwert** [comment]
Added as part of `v1.11.0`
