### ISSUE TITLE
Cannot use Navigator.pushNamed with PlatformTabScaffold (Ios only)

### ISSUE THREAD

**Issue by hengvenchang** [stryder-dev/flutter_platform_widgets#172]
Very nice library! really enjoy using it!
I came to a problem when trying to push to new page from a tab,
this problem occurs on IOS only (For Android it's working very smoothy)

<img width="1440" alt="Screen Shot 2020-05-13 at 3 13 14 PM" src="https://user-images.githubusercontent.com/17307495/81788161-4bbd0580-952c-11ea-99e0-03966a1aef6d.png">

here's main.dart
<img width="450" alt="Screen Shot 2020-05-13 at 3 14 19 PM" src="https://user-images.githubusercontent.com/17307495/81788278-7c9d3a80-952c-11ea-8596-56863fc46a50.png">

here's Tab.dart
<img width="387" alt="Screen Shot 2020-05-13 at 3 14 05 PM" src="https://user-images.githubusercontent.com/17307495/81788326-8cb51a00-952c-11ea-80ff-36fb506e0e7a.png">

here's my sub tab
<img width="603" alt="Screen Shot 2020-05-13 at 3 14 26 PM" src="https://user-images.githubusercontent.com/17307495/81788384-a3f40780-952c-11ea-819f-9dc720bedb43.png">

**Comment by Valentin-Seehausen** [comment]
Could you try adding `/`, i.e. `/detail`.

Also it is not clear, where your router is defined and you seem to have issues with an import.

**Comment by aqwert** [comment]
Closing as this is not an issue with this library
