### ISSUE TITLE
Feature Request: Propagate down attributes or child on PlatformWidget

### ISSUE THREAD

**Issue by Valentin-Seehausen** [stryder-dev/flutter_platform_widgets#175]
A more generalized version of [this problem](https://github.com/aqwert/flutter_platform_widgets/issues/147#issuecomment-629153321) is:

I want do have two different Widget on the platform.
I want them to have exactly the same child.
I don't want to duplicate the child tree for both platforms.

Proposal: Alter the API of PlatformWidget to handle down children or other attributes.

Instead of
```
PlatformWidget(
  android: (_) => InkWellInkWell(
    child: Container(
      padding: EdgeInset.all(16),
      child: Text('click me') // this tree could be quite long
    ),
    onTap: () {
      thisCouldBeQuiteLongToo();
    }
  ),
  ios: (_) => GestureDetector(
    child: Container(
      padding: EdgeInset.all(16),
      child: Text('click me') // this tree could be quite long
    ),
    onTap: () {
      thisCouldBeQuiteLongToo();
    }
  ),
);
```
One could write in a DRY fashion:
```
PlatformWidget(
  android: (_) => InkWell(), 
  ios: (_) => GestureDetector(),
  // these will get added to both Widgets:
  child: Container(
    padding: EdgeInset.all(16),
    child: Text('click me') // this tree could be quite long
  ),
  onTap: () {
    thisCouldBeQuiteLongToo();
  }
);
```

Right now one has to write a function for the child tree, if one wants to have DRY code. Which feels not very flutterish to me. 

Would be happy to PR.

**Comment by aqwert** [comment]
Something like this may be useful. What probably will work is something like this:

```
PlatformWidgetBuilder(
      ios: (_, child, action) => GestureDetector(child: child, onTap: action),
      android: (_, child, action) => InkWell(child: child, onTap: action),
      child: Container(
        padding: EdgeInset.all(16),
        child: Text('click me') // this tree could be quite long
      ),
      action: () {
         thisCouldBeQuiteLongToo();
      }
    );
  }
```

```
class PlatformWidgetBuilder extends StatelessWidget {
  final VoidCallback action;
  final Widget child;
  final Widget Function(BuildContext, Widget, VoidCallback) ios;
  final Widget Function(BuildContext, Widget, VoidCallback) android;

  PlatformWidgetBuilder({
    @required this.ios,
    @required this.android,
    this.action,
    this.child,
  })  : assert(ios != null),
        assert(android != null);

  @override
  Widget build(BuildContext context) {
    return PlatformWidget(
      ios: (context) => ios(context, child, action),
      android: (context) => android(context, child, action),
    );
  }
}
```

**Comment by Valentin-Seehausen** [comment]
Nice! That would work work for sure in most cases.

Just thinking about a more general approach, i.e. handling down all arguments. Is that possible in Dart? On the other side would it actually make sense?

Still love your approach!

**Comment by aqwert** [comment]
Pretty much the arguments that a widget needs has to be given at tie of construction time

**Comment by DFelten** [comment]
Thanks for the template, the `PlatformWidgetBuilder`  works great. This would be a great addition for the package.

**Comment by aqwert** [comment]
I added this widget in. Slightly different to what is in this issue but achieves the same
