### ISSUE TITLE
对Flutter升级到1.19.0-2.0 Dart2.9.0后，Run报错：Error: The method 'PlatformText' isn't defined for the class

### ISSUE THREAD

**Issue by 472125266** [stryder-dev/flutter_platform_widgets#186]
在Flutter 1.19.0-2.0 Dart2.9.0版本下，我用的是：flutter_platform_widgets，版本：0.50.0，Run项目会报错。如图
![Snip20200522_2](https://user-images.githubusercontent.com/19839641/82655011-262eab00-9c54-11ea-9672-cb89cf67d3ae.png)

**Comment by 472125266** [comment]
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:134:27: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                          PlatformText(Tools.changeNavMessageUI(9999999),                                          
                          ^^^^^^^^^^^^                                                                             
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:139:27: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                          PlatformText("粉丝",                                                                     
                          ^^^^^^^^^^^^                                                                             
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:160:27: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                          PlatformText(Tools.changeNavMessageUI(99999),                                            
                          ^^^^^^^^^^^^                                                                             
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:165:27: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                          PlatformText("邀币",                                                                     
                          ^^^^^^^^^^^^                                                                             
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:182:29: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                            PlatformText("个人中心",                                                               
                            ^^^^^^^^^^^^                                                                           
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:222:25: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                        PlatformText("收藏",                                                                       
                        ^^^^^^^^^^^^                                                                               
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:239:25: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                        PlatformText("圈子",                                                                       
                        ^^^^^^^^^^^^                                                                               
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:256:25: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                        PlatformText("课程",                                                                       
                        ^^^^^^^^^^^^                                                                               
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:273:25: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                        PlatformText("文章",                                                                       
                        ^^^^^^^^^^^^                                                                               
lib/pages/me/view/me_pagecontroller_topuserInfo.dart:316:17: Error: The method 'PlatformText' isn't defined for the class '_MePageControllerTopUserInfoWidgetState'.
 - '_MePageControllerTopUserInfoWidgetState' is from 'package:myyaopaiproject/pages/me/view/me_pagecontroller_topuserInfo.dart' ('lib/pages/me/view/me_pagecontroller_topuserInfo.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformText'.              
                PlatformText(                                                                                      
                ^^^^^^^^^^^^

**Comment by aqwert** [comment]
Can you share the code you currently have. Have you included the import?

**Comment by 472125266** [comment]
sorry，由于项目是私有的，可能暂时无法公开。您可以尝试着升级环境，尝试一下。

**Comment by aqwert** [comment]
I really can't help you with any code. Could you make an example

**Comment by aqwert** [comment]
Closing as there is no more information I can help you with
