### ISSUE TITLE
PlatformTabScaffold, tabsBackgroundColor

### ISSUE THREAD

**Issue by alanmeier** [stryder-dev/flutter_platform_widgets#189]
Hi there,

On tabsBackgroundColor for PlatformTabScaffold if you set the tabsBackgroundColor parameter it has no effect on my Android emulator, it does work on the IOS emulator. In fact changing any of the Colours in the Theme itself will also have no effect on the tabsBackgroundColor for the Android emulator.

Below is the code in case you want to see it.

```
 BottomNavigationBarItem _navigationBarItemBuilder(TabItem tabItem) {
    final itemData = TabItemData.allTabs[tabItem];
    return BottomNavigationBarItem(
      title: Text(itemData.title),
      icon: PlatformWidget(
        ios: (_) => Icon(itemData.iosIcon),
        android: (_) => Icon(itemData.materialIcon),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {

    print('tabbed_navigation init');
    // Globals globals = Provider.of<Globals>(context, listen: false); 
    return PlatformTabScaffold(
      iosContentPadding: true,
      tabsBackgroundColor: Colors.teal[100],
      tabController: tabController,
      bodyBuilder: (context, index) => _selectPage(index, !widget.usingIOS),
      items: [
        _navigationBarItemBuilder(TabItem.course),
        _navigationBarItemBuilder(TabItem.meditation),
        _navigationBarItemBuilder(TabItem.music),
        _navigationBarItemBuilder(TabItem.sleep),
        _navigationBarItemBuilder(TabItem.more),
      ],
      ios: (_) => CupertinoTabScaffoldData(
        //   Having this property as false (default true) forces it not to use CupertinoTabView which will show
        //   the back button, but does required transitionBetweenRoutes set to false (see above)
        useCupertinoTabView: false,
      ),
    );
  }
}

```

**Comment by aqwert** [comment]
Whether you run this on in the Android Emulator or iOS simulator won't have anything to do with it.  What only matters is whether it is rendering Material or Cupertino styled widgets. 

As for the issue. I am unable to replicate this in the example project. The colour gets set correctly in Material or Cupertino. Could you run the example to see if you get the same issue

**Comment by alanmeier** [comment]
No it is still the same. I pass custom themes when the App is created so it is likely something to do with that. Below is the code. Note that when I create just blank Themes for materialTheme and materialDarkTheme it still exhibits the same issue. Everything works fine for IOS, it is just Android that has the issue.
        return Theme(
          data: brightness == Brightness.light
              ? materialTheme
              : materialDarkTheme,
          child: PlatformProvider(
            //initialPlatform: initialPlatform,
            settings: PlatformSettingsData(iosUsesMaterialWidgets: false),
            builder: (BuildContext context) => PlatformApp(
              title: 'Infinite Mind',
              android: (_) => new MaterialAppData(
                  theme: materialTheme, darkTheme: materialDarkTheme),
              ios: (_) => new CupertinoAppData(theme: cupertinoTheme),
              home: EmailLinkErrorPresenter.create(
                context,
                child: AuthWidget(userSnapshot: userSnapshot),
              ),
            ),
          ),
        );

**Comment by ajaygautam** [comment]
@alanmeier  whats the flutter doctor output? (which stream are you on?)

**Comment by alanmeier** [comment]
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.17.3 at /users/alan/flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 8 • 387C826F-11BE-43AC-9966-0DCCDB47F237 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
