### ISSUE TITLE
ListTiles in iOS

### ISSUE THREAD

**Issue by xxJeevesxx** [stryder-dev/flutter_platform_widgets#198]
Great library thanks for putting this together! I'm wondering about ListTiles in iOS. It looks like they don't currently work because, "No Material widget found. ListTile widgets require a Material widget ancestor". Am I expecting something that shouldn't work or am I missing something? Should I be doing a ListView / ListTile differently? Thanks in advance!

**Comment by aqwert** [comment]
You can use the `ListView` widget in iOS as it is part of the widgets library of Flutter. However `ListTile` is a Material widget so as you state using it in iOS is possible only if there is a `Material` parent widget. If you don't want to do that then you need to create your own Cupertino version or raise an issue with flutter for one to be made. If you do create one you can create a widget that uses `PlatformWidget` to pick the right material or cupertino widget for you.

**Comment by aqwert** [comment]
Closing as it is not an issue with this library

**Comment by xxJeevesxx** [comment]
Thanks for your reply! Sorry to waste your time. 

Do you know if there are any plans to incorporate a PlatformListTile to the library?

**Comment by aqwert** [comment]
There is an open PR with a PlatformListTile implementation but IMO it is opinionated implementation of a iOS List tile. I have been thinking of having an opinionated area for the project but I worry it may work differently to how people expect it to be
