### ISSUE TITLE
How to change the PlatformAppBar brightness in IOS?

### ISSUE THREAD

**Issue by AhmedAbouelkher** [stryder-dev/flutter_platform_widgets#201]
Hi, 
I really have to thank you for your amazing package, you really saved hours of developing.

the `PlatformAppBar` brightness on Andriod is suitable but on IOS it should be `light` as for my application use case, so, is there a way to change the brightness of the `PlatformAppBar`?

thanks

**Comment by aqwert** [comment]
You can set the `Brightness` of the app bar through the extended `cupertino` property

```dart
PlatformAppBar(
    cupertino: (_, __) => CupertinoNavigationBarData(
         brightness: Brightness.light
    )
)
```
