### ISSUE TITLE
Error compilation last version

### ISSUE THREAD

**Issue by ewersoncastelo** [stryder-dev/flutter_platform_widgets#207]
I have a code created with the readme of the latest version ^0.60.1, but despite not having any debug errors, it does not compile the code and shows the following error:

`../../flutter/packages/flutter/lib/src/cupertino/text_field.dart:217:9: Context: Found this candidate, but the arguments don't match.
      const CupertinoTextField({
            ^^^^^^^^^^^^^^^^^^`

Note that if I change the version to ^0.50.1, it will compile, once compiled, I can go back to the current version that works. However, there is this error, which can be a cache problem or something else.

In my case, I created an entire project in version ^0.60.1 and it did not compile despite not showing any apparent warning or error in the code.

to reproduce the error, just clone the repository and try to compile in the current version (^0.60.1) and vice versa in the version (0.50.1) https://github.com/ewersoncastelo/Platform_Aware_Flutter

**Comment by aqwert** [comment]
What is the version of flutter? Can you post the output of `flutter doctor -v`

**Comment by ewersoncastelo** [comment]
v1.17.5

**Comment by aqwert** [comment]
Version 0.60.1 and above only support flutter version 1.20+. You are on v1.17.5 so need to go down to v0.51.0.

Look at the [ChangeLog](https://github.com/stryder-dev/flutter_platform_widgets/blob/master/CHANGELOG.md) as it states the supported flutter version
