### ISSUE TITLE
Feature request: iconSize on PlatformIconButton

### ISSUE THREAD

**Issue by timovandeput** [stryder-dev/flutter_platform_widgets#210]
I want to put a bigger PlatformIconButton in a Row, and increased the size of the enclosed icon to achieve it. This (accidentally) works on iOS, but not on Android because it does not grow the IconButton.

Please add the equivalent of IconButton(iconSize: xxx) to properly forward the size to the appropriate field on each platform.

**Comment by aqwert** [comment]
The iconSize for android can be achieved by 

```
PlatformIconButton(
    material: (_, __) => MaterialIconButtonData(iconSize: <something_else>),
)
```

**Comment by timovandeput** [comment]
Works like a charm; thanks!
