### ISSUE TITLE
Support for platform app router

### ISSUE THREAD

**Issue by bsr203** [stryder-dev/flutter_platform_widgets#216]
As [router](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade) is supported in stable branch, would like to have support in platform app

```
Creates a [CupertinoApp] that uses the [Router] instead of a [Navigator].
CupertinoApp.router
```

  ```
/// Creates a [MaterialApp] that uses the [Router] instead of a [Navigator].
  const MaterialApp.router({
```

**Comment by PavelPZ** [comment]
+1
I cannot use this package without this feature

**Comment by aqwert** [comment]
@bsr203 / @PavelPZ I have merged in `PlatformApp.router`. I have not yet used the new Router system. Could you git reference the master branch to test it out. If all ok I can publish the package

**Comment by bsr203** [comment]
@aqwert It works well for me. I don't use all the configuration options though, but may get around when using extensively. Thank you for the quick response. Cheers.

**Comment by aqwert** [comment]
@bsr203 Merged into master and published to pub.dev v0.71.0
