### ISSUE TITLE
PlatformAppBar height

### ISSUE THREAD

**Issue by ninoid** [stryder-dev/flutter_platform_widgets#217]
Is possible to change height of PlatofrmAppBar?

**Comment by aqwert** [comment]
Looking at the underlying Material `AppBar` and `CupertinoNavigationBar` there is no height property. Perhaps use a `SliverAppBar` but there is no platform version of that

**Comment by aqwert** [comment]
If you can do it in Material or Cupertino widgets directly it can be done using this package.
