### ISSUE TITLE
QUESTION: How to set placeholder for PlatformTextField?

### ISSUE THREAD

**Issue by hosembafer** [stryder-dev/flutter_platform_widgets#220]
Hello, I'm just started with flutter and chosen this lib as a wrapper for cross-platform dev. And the first thing that I wanted to try is to create a text field, and I'm not sure how to set a placeholder for it. Can someone provide me information about it or maybe alternative documentation?

**Comment by aqwert** [comment]
placeholder text differs between material and cupertino. The only way at the moment is to do this

```
PlatformTextField(
   material: (_, __) => MaterialTextFieldData(decoration: InputDecoration(
        hintText: 'Enter your name'
      ),),
   cupertino: (_, __) => CupertinoTextFieldData(placeholder: 'Enter your name'),
);
```

Thinking about it more I may add a field at the `PlatformTextField` level for the simple cases.

**Comment by hosembafer** [comment]
@aqwert, thanks! Yes, placeholder field will make sense, also I found another properties like prefix and other decoration sub fields that currently need to be passed in platform specific manner.

Can you provide some Contributions guideline in README to let people know from where to start the contribution?

**Comment by aqwert** [comment]
You can contribute via a PR if you want. The material and cupertino properties that are common are on the PlatformTextField and most are there. What other ones were you thinking. Issue is say in this case you can add more to `InputDecoration` which the cupertino widget does not have
