### ISSUE TITLE
PlatformTabScaffold not working properly with > 3 tabs

### ISSUE THREAD

**Issue by slimyjimmy** [stryder-dev/flutter_platform_widgets#222]
Hey there, I noticed that PlatformTabScaffold doesn't work properly if you add more than 3 tabs. 
What happens then is that the tabs turn whiteish so you can hardly see them.

**Steps to reproduce:** 
Just take the [Basic example](https://github.com/stryder-dev/flutter_platform_widgets/blob/master/example/lib/tabbed/basicTabbedPage.dart) from your docs and add two (or more) more tabs.

**Comment by aqwert** [comment]
This is an issue with flutter. see this issue: https://github.com/flutter/flutter/issues/67903

You can apply the type like so

```
PlatformTabScaffold(
    ...
    materialTabs: (context, platform) => MaterialNavBarData(
        type: BottomNavigationBarType.fixed
      ),
);

```

**Comment by slimyjimmy** [comment]
Oh sorry and thanks for the link!
