### ISSUE TITLE
PlatformText does no show consistent colors across platforms.

### ISSUE THREAD

**Issue by safield** [stryder-dev/flutter_platform_widgets#223]
I am displaying a PlatformDialog by calling showPlatformDialog().

When the dialog is shown on Android, the PlatformText automatically uses ThemeData.colorScheme.primary as the text color.

On iOS the PlatformText color seems to be using an iOS system color.

   ```
 var buttons = List<Widget>();

    if (onCancel != null) {
      buttons.add(PlatformDialogAction(
          child: PlatformText("Cancel"),
          onPressed: onCancel
        )
      );
    }

    buttons.add(
      PlatformDialogAction(
        child: PlatformText("Ok"),
        onPressed: onConfirm,
      )
    );

    showPlatformDialog(
      context: context,
      builder: (_) => PlatformAlertDialog(
        title: Text(title),
        content: Text(message),
        actions: buttons
      ),
    );
```

**Comment by aqwert** [comment]
This is what flutter does. You will likely need to use the Cupertino theme or change colors directly

https://api.flutter.dev/flutter/cupertino/CupertinoThemeData-class.html

**Comment by safield** [comment]
Isn't one of the goals of this project for its widgets to be platform agnostic, and look consistent across platform?

**Comment by aqwert** [comment]
No. It's goal is to use a single widget that will render the Material or Cupertino version depending on the platform. If you used the Cupertino widget directly it will have the same behavour than you would use this library. I do not want any opinionated views on how widgets should look so all it does is delegate to the correct underlying platform widget passing.
