### ISSUE TITLE
PlatformIconButton is using CupertinoButton.filled

### ISSUE THREAD

**Issue by ekuleshov** [stryder-dev/flutter_platform_widgets#230]
It would be nice to have an option to override PlatformIconButton to use a non-filled CupertinoButton variant.

**Comment by ekuleshov** [comment]
Sorry, closed it by accident

**Comment by aqwert** [comment]
According to the code it does not use filled. https://github.com/stryder-dev/flutter_platform_widgets/blob/3f01a8880638fd99a322e5a5f8fd45ea25edcb43/lib/src/platform_icon_button.dart#L173

**Comment by ekuleshov** [comment]
Strange. It is indeed working as expected. I guess issue can be closed.
