### ISSUE TITLE
PlatforIcons.tags is mixed up

### ISSUE THREAD

**Issue by ekuleshov** [stryder-dev/flutter_platform_widgets#231]
There is something wrong with the `PlatforIcons.tags` definition:
```
  /// Icons: Icons.share : CupertinoIcons.tags
  IconData get tags => isMaterial(context) ? Icons.share : CupertinoIcons.tags;
```

**Comment by vincevargadev** [comment]
Do you know if there is a tags icon in the material library? Mind the plural, tag*s*.

**Comment by ekuleshov** [comment]
This issue is mainly about using `share` icon.

But yes there is. Here My personal preference and also why I also suggested #233 

<img width="472" alt="Screen Shot 2021-01-22 at 12 05 48 PM" src="https://user-images.githubusercontent.com/440954/105521648-2df29380-5caa-11eb-99e8-77142b357b26.png">

There are more, both solid and outline variants.

<img width="825" alt="Screen Shot 2021-01-22 at 12 05 05 PM" src="https://user-images.githubusercontent.com/440954/105521556-13b8b580-5caa-11eb-9aa1-508347140e8a.png">

<img width="825" alt="Screen Shot 2021-01-22 at 12 02 41 PM" src="https://user-images.githubusercontent.com/440954/105521341-c0466780-5ca9-11eb-880f-311b79634f34.png">

**Comment by aqwert** [comment]
I think having .tags was a mistake. Can just use tag as for cupertino it is just the same.

**Comment by aqwert** [comment]
`tags` has been removed
