### ISSUE TITLE
Exception caught by widgets library Consumer<CartItemCounter>

### ISSUE THREAD

**Issue by hojamedov** [stryder-dev/flutter_platform_widgets#238]
I don't know where is mistake. Please help me to resolve the error! Thank you!

When I trying to run my project the app counter not working

and the studio give me this error

    W/DynamiteModule( 7762): Local module descriptor class for providerinstaller not found.
    I/DynamiteModule( 7762): Considering local module providerinstaller:0 and remote module providerinstaller:0
    W/ProviderInstaller( 7762): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and 
    remote version is 0.

    ======== Exception caught by widgets library 
    =======================================================
    The following NoSuchMethodError was thrown building Consumer<CartItemCounter>(dirty, dependencies: 
    [_InheritedProviderScope<CartItemCounter>]):
    The getter 'length' was called on null.
    Receiver: null
    Tried calling: length

    The relevant error-causing widget was: 
      Consumer<CartItemCounter> file:///C:/Users/Admin/Desktop/e_shop/lib/Store/storehome.dart:68:32
    When the exception was thrown, this was the stack: 
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
    #1      new CartItemCounter (package:e_shop/Counters/cartitemcounter.dart:6:90)
    #2      MyApp.build.<anonymous closure> (package:e_shop/main.dart:34:47)
    #3      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:646:35)
    #4      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:509:33)
    ...
    =======================================================================

**THE PAGE**

    import 'package:cloud_firestore/cloud_firestore.dart';
    import 'package:e_shop/Store/cart.dart';
    import 'package:e_shop/Store/product_page.dart';
    import 'package:e_shop/Counters/cartitemcounter.dart';
    import 'package:flutter/material.dart';
    import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
    import 'package:fluttertoast/fluttertoast.dart';
    import 'package:provider/provider.dart';
    import 'package:e_shop/Config/config.dart';
    import '../Widgets/loadingWidget.dart';
    import '../Widgets/myDrawer.dart';
    import '../Widgets/searchBox.dart';
    import '../Models/item.dart';

    double width;

    class StoreHome extends StatefulWidget {
    @override
    _StoreHomeState createState() => _StoreHomeState();
    }

    class _StoreHomeState extends State<StoreHome> {
      @override
      Widget build(BuildContext context) {
        width = MediaQuery.of(context).size.width;
        return SafeArea(
          child: Scaffold(
            appBar: AppBar(
              flexibleSpace: Container(
                decoration: new BoxDecoration(
                  gradient: new LinearGradient(
                    colors: [Colors.blue, Colors.purpleAccent],
                    begin: const FractionalOffset (0.0, 0.0),
                    end: const FractionalOffset (1.0, 0.0),
                    stops: [0.0, 1.0],
                    tileMode: TileMode.clamp,
                  ),
                ),
              ),
              title: Text(
                "Salam Market",
                style: TextStyle(fontSize: 55.0, color: Colors.white, fontFamily: "Signatra"),
              ),
              centerTitle: true,
              actions: [
                Stack(
                  children: [
                    IconButton(
                      icon: Icon(Icons.shopping_cart, color: Colors.pink,),
                      onPressed: ()
                      {
                        Route route = MaterialPageRoute(builder: (c) => CartPage());
                        Navigator.pushReplacement(context, route);
                      },
                    ),
                    Positioned(
                      child: Stack(
                        children: [
                          Icon(
                            Icons.brightness_1,
                           size: 20.0,
                            color: Colors.green,
                          ),
                          Positioned(
                            top: 3.0,
                            bottom: 4.0,
                            left: 4.0,
                            child: Consumer<CartItemCounter>(
                              builder: (context, counter, _)
                              {
                                return Text(
                                  counter.count.toString(),
                                  style: TextStyle(color: Colors.white,fontSize: 12.0, 
                                      fontWeight: 
                                      FontWeight.w500),
                                );
                              },
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
            drawer: MyDrawer(),
          ),
        );
      }
    }

    Widget sourceInfo(ItemModel model, BuildContext context,
        {Color background, removeCartFunction}) {
      return InkWell();
    }

    Widget card({Color primaryColor = Colors.redAccent, String imgPath}) {
      return Container();
    }

    void checkItemInCart(String productID, BuildContext context)
    {
    }

**Comment by aqwert** [comment]
I am sorry but this issue does not seem related to this project. I suggest asking such questions on Stackoverflow
