### ISSUE TITLE
Error with CupertinoNavigationBar

### ISSUE THREAD

**Issue by erperejildo** [stryder-dev/flutter_platform_widgets#239]
```
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.72.0/lib/src/platform_app_bar.dart:202:9: Error: No named parameter with the name 'actionsForegroundColor'.
        actionsForegroundColor: data?.actionsForegroundColor,
        ^^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/packages/flutter/lib/src/cupertino/nav_bar.dart:220:9: Context: Found this candidate, but the arguments don't match.
  const CupertinoNavigationBar({
        ^^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.72.0/lib/src/platform_app_bar.dart:222:7: Error: No named parameter with the name 'actionsForegroundColor'.
      actionsForegroundColor: data?.actionsForegroundColor,
      ^^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/packages/flutter/lib/src/cupertino/nav_bar.dart:220:9: Context: Found this candidate, but the arguments don't match.
  const CupertinoNavigationBar({
        ^^^^^^^^^^^^^^^^^^^^^^

```

Using:
```
sdk: '>=2.7.0 <3.0.0'
flutter_platform_widgets: ^0.72.0
```

**Comment by aqwert** [comment]
This has been removed by the latest version of Flutter. I will push an update soon to resolve this

**Comment by aqwert** [comment]
Currently the project only supports stable and beta. By the looks this change is only on dev. I suggest forking the project and git referencing your fork.

**Comment by erperejildo** [comment]
no problem then. I'll move to the stable channel

**Comment by aqwert** [comment]
Looks like dev has been promoted to beta. I will create a beta branch and update the null-safety branch also

**Comment by daveols** [comment]
@aqwert do you plan on creating a release on pub.dev soon with this fix or should we be referencing the `beta` branch of this project directly in our dependencies?

**Comment by aqwert** [comment]
I have created a branch `beta` that you can reference. I will push a beta version also.
```
  flutter_platform_widgets: #^0.72.0
    git:
      url: git://github.com/stryder-dev/flutter_platform_widgets.git
      ref: beta
```

It does look like there are other breaking changes from flutter that affects other packages.

**Comment by aqwert** [comment]
I have also pushed a beta version `https://pub.dev/packages/flutter_platform_widgets/versions/0.80.0-beta.0`. Or in the pubspec.yaml file use `flutter_platform_widgets: ^0.80.0-beta.0`

**Comment by kuhnroyal** [comment]
With Flutter 2.0.0 a lot of people will be looking for this `0.80.0-beta.0` version before moving on to Dart 2.12. Maybe you can finalize it as a release.

**Comment by aqwert** [comment]
I will look at making the beta version into the main version later today

**Comment by aqwert** [comment]
Version 0.80.0 is out now that fully supports flutter 2.0 (not non-nullable). Non nullable is in preview

**Comment by kuhnroyal** [comment]
Thanks @aqwert !
