### ISSUE TITLE
BottomNavigationBarItem label color changes to white when items are more than 3

### ISSUE THREAD

**Issue by Shajeel-Afzal** [stryder-dev/flutter_platform_widgets#241]
The color of the label text changes to white color when I add more than 3 items in the `PlatformTabScaffold`.
Is it a bug or something else?

For example, the below picture shows the labels properly when the items are less than 4. 
![Screenshot_1612376133](https://user-images.githubusercontent.com/3718283/106790714-c1966d80-6675-11eb-9bc3-9f22a10b6c1a.png)

And the label color changes to white once items are more than 3.
![Screenshot_1612376223](https://user-images.githubusercontent.com/3718283/106790851-f5719300-6675-11eb-835c-f42687a89f68.png)

**Comment by aqwert** [comment]
Please refer to https://github.com/stryder-dev/flutter_platform_widgets/issues/222

This is an issue with flutter. see this issue: https://github.com/flutter/flutter/issues/67903

You can apply the type like so

```
PlatformTabScaffold(
    ...
    materialTabs: (context, platform) => MaterialNavBarData(
        type: BottomNavigationBarType.fixed
      ),
);

**Comment by rahulshamkuwar** [comment]
Hey, this answer worked for me, but I don't have access to an iOS emulator right now, just wanted to check if this issue also happens on iOS? Or was it just an Android thing? I ask because the flutter issue seemed to be using an iOS emulator (though the widget they used was a `BottomNavigationBar`) and there is no `type` parameter for `CupertinoTabBarData`.

**Comment by aqwert** [comment]
It is the `Material` `BottomNavigationBar` that does this. With this plugin you can set the target style of `cupertino` or `material` independent of the actual hardware you are running on. `CupertinoTabBarData` does not have this issue
