### ISSUE TITLE
Inability to use Snackbar

### ISSUE THREAD

**Issue by brownwood** [stryder-dev/flutter_platform_widgets#252]
When attempt is made to call Snackbar within the context of the PlatformScaffold, it throws an error:

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Scaffold.of() called with a context that does not contain a Scaffold.

Please help review.

**Comment by pxsanghyo** [comment]
SnackBar needs Scaffold from material ie. no SnackBar for cupertino.

I did this for now to get it to fire SnackBar but it will probably display over some bottom cupertino widgets? Not sure, haven't gotten that far.

```dart
return PlatformApp.router(
  material: (_, __) => MaterialAppRouterData(theme: material),
  cupertino: (_, __) => CupertinoAppRouterData(
    theme: cupertino,
    builder: (context, router) => Theme(
      data: material,
      child: ScaffoldMessenger(
        child: Scaffold(body: router),
      ),
    ),
  ),
);
```

Theme (material) is also needed to style SnackBar.
And you can show SnackBar like so:

```dart
final messenger = ScaffoldMessenger.of(context);
messenger.showSnackBar(SnackBar(content: Text('yay')));
```

I wish cupertino had SnackBar... :(

**Comment by aqwert** [comment]
This package is about using the underlying material or cupertino widgets if they exist. SanckBars are a material concept so it is hard to do despoke Platform widget for it. Anything other than using the underlying widgets will mean designing a platform widget that is too opinionated and not work for everyone.

**Comment by brownwood** [comment]
Thanks guys for the feedback. Summary, I'll leave 'PlatformScaffold' out for now.

**Comment by aqwert** [comment]
Closing as this is not an issue with the package
