### ISSUE TITLE
RaisedButton, FlatButton deprecated

### ISSUE THREAD

**Issue by pxsanghyo** [stryder-dev/flutter_platform_widgets#253]
Can we update to PlatformButton for material to use RaisedButton and FlatButton? The individual styling is not removed in favor of ButtonStyle to style which is easier to reuse.

**Comment by aqwert** [comment]
I have plans on making a new widget to switch over to the new material buttons. Although these are deprecated they will not be removed from flutter for a long time.

**Comment by kuhnroyal** [comment]
@aqwert I would like to revive this, starting with the Flutter `3.1.0` release which is available on `beta`, the buttons have been removed and as such the package currently does not work there.

**Comment by aqwert** [comment]
Good to know they have been removed. I will look at removing these next
