### ISSUE TITLE
Cannot return null for appBarBuilder function

### ISSUE THREAD

**Issue by jonbhanson** [stryder-dev/flutter_platform_widgets#254]
Thanks for the great package!

In the `PlatformTabScaffold`, I previously (prior to null safety) declared an `appBarBuilder` function that returned `null` for some pages.  However, with null safety I can no longer return `null`.  How can I have a `appBarBuilder` for some pages, and not for others?  Maybe the `appBarBuilder` needs to be type `PlatformAppBar?` so that a null can still be used?

```dart
PlatformTabScaffold(
  appBarBuilder: (context, index) {
    if (index == 1 && isMaterial(context)) return SearchPage.appBar(context);
    return null; // gives error The return type 'Null' isn't a 'PlatformAppBar', as required by the closure's context.
  },
  // other properties
);
```

**Comment by aqwert** [comment]
I had a look and see that is an issue. Will push a patch soon

**Comment by aqwert** [comment]
version `1.0.1-nullsafety.1` should fix this

**Comment by jonbhanson** [comment]
Thanks for the quick response!  You rock!  🤘🏻
