### ISSUE TITLE
How to change active label's color for BottomNavigationBarItem?

### ISSUE THREAD

**Issue by hengvenchang** [stryder-dev/flutter_platform_widgets#257]
Great library! Currently i'm only able to change icon color, not label. So is there any way to fix this?
BottomNavigationBarItem(
          label: titles[1],
          icon: Icon(context.platformIcons.person),
          activeIcon: Icon(context.platformIcons.person,
              color: ColorTheme.PrimaryColor),
        )
<img width="353" alt="Screen Shot 2021-03-17 at 4 06 10 PM" src="https://user-images.githubusercontent.com/17307495/111442251-b9cced00-873a-11eb-80f3-7fabb1e2bde4.png">

**Comment by aqwert** [comment]
That is what Flutter has given us. I think that can be controlled from the Theme though not sure

**Comment by hengvenchang** [comment]
Able to fix the issue by providing a theme color to platform app:

 return PlatformApp(
        cupertino: (_, __) => (CupertinoAppData(
            theme: CupertinoThemeData(primaryColor: ColorTheme.PrimaryColor))),
        material: (_, __) => MaterialAppData(
            theme: ThemeData(primaryColor: ColorTheme.PrimaryColor)));
            
which i don't think this need to be this complicated, it just works for now, looking forward to better solution
