### ISSUE TITLE
Using GetX?

### ISSUE THREAD

**Issue by Urkman** [stryder-dev/flutter_platform_widgets#260]
Is there somewhere a documentation on how to use the PlatFormWidgets with GetX?
Currently struggling with the **PlatformTabScaffold** and the tabController :(

**Comment by aqwert** [comment]
Can you describe how it should work with GetX? If you created tabbed scaffold directly using the material and Cupertino widgets how will GetX be added to it?.

**Comment by fredgrott** [comment]
I will be able to answer this next week with a real example.

Wil be doing an article series as well 

Do we need some docs on how to do it with different state management archs?

If so I can get to it and complete it

**Comment by aqwert** [comment]
Not sure what you need this package to do with state management. It just wraps existing flutter material and cupertino widgets. It should work with any architecture that conforms with how flutter is used.

**Comment by Urkman** [comment]
@aqwert Because GetX is more then just State Management... It would be great to have an introduction on how to use them together... eg using GetMaterialApp and GetCupertinoApp

I'm from the iOS world and I don't want to just make an "Material App" as a lot of others. And since I'm new to Flutter I'm currently trying a lot of packages, that could help me...

**Comment by Urkman** [comment]
@fredgrott Great... Please leave a link here :)
