### ISSUE TITLE
The official sample code and sample picture do not match

### ISSUE THREAD

**Issue by chentianxin** [stryder-dev/flutter_platform_widgets#277]
# Expected effect
https://github.com/stryder-dev/flutter_platform_widgets/blob/master/images/android.png

# actual effect
![1FE9610B-8E8C-450F-ABB5-5E859C8B3364](https://user-images.githubusercontent.com/49486355/116676409-863bde80-a9d9-11eb-9ed1-bc14f46fd945.png)

**Comment by aqwert** [comment]
I am starting more official documentation so that will be what you reference. I updated the example to be cleaner.
