### ISSUE TITLE
Material PlatformText is showing all text uppercase.

### ISSUE THREAD

**Issue by emce** [stryder-dev/flutter_platform_widgets#278]
Is this on purpose?

https://github.com/stryder-dev/flutter_platform_widgets/blob/bb6cf795f656af9a25078628c96143875ca7b5d6/lib/src/platform_text.dart#L15

**Comment by aqwert** [comment]
Yes. This is intentional.  It is useful for having uppercase dialog buttons for material. If you don't want that just use `Text`

**Comment by LeFrenchTouch** [comment]
How can one use `PlatformText` to have the right font automatically (Roboto for Android and SF for iOS) and not have the text automatically transformed to upper case on Android?

**Comment by aqwert** [comment]
This comes from the `Theme` or you set the `Text.style` directly. if you don't want to it to be uppercase just use the regular `Text` widget
