### ISSUE TITLE
Theme color on Cupertino vs Material

### ISSUE THREAD

**Issue by erf** [stryder-dev/flutter_platform_widgets#279]
I have an Material app which i would like to make more Cupertino-like for iOS. I smacked PlatformApp at the top of the hierarchy, with themes for Material and cupertino. The layout changed but i noticed the appbar background color and the button colors are now the default blue. It seem i need to use the PlatformScaffold and override the appBar per platform and set the cupertino nav bar background explicitly to change it. This makes it seem like a lot of work to make it adaptive for both platforms with same theming. Am i missing something?

**Comment by aqwert** [comment]
Assuming a simple use of Scaffold and nothing custom you can do it this way. If there is custom scaffolds beyond the default use then that will require more work.

Setup the app in this way

```
Widget build(BuildContext context) {
    final materialTheme = new ThemeData(
      primarySwatch: Colors.purple,
    );

    return Theme(
      data: materialTheme,
      child: PlatformProvider(
        //initialPlatform: TargetPlatform.android,
        settings: PlatformSettingsData(iosUsesMaterialWidgets: true),
        builder: (context) => PlatformApp(
          localizationsDelegates: <LocalizationsDelegate<dynamic>>[
            DefaultMaterialLocalizations.delegate,
            DefaultWidgetsLocalizations.delegate,
            DefaultCupertinoLocalizations.delegate,
          ],
          title: 'Flutter Platform Widgets',
          home: PlatformPage(),
          material: (_, __) => new MaterialAppData(
            theme: materialTheme,
          ),
          cupertino: (_, __) => new CupertinoAppData(
            theme:
                MaterialBasedCupertinoThemeData(materialTheme: materialTheme),
          ),
        ),
      ),
    );
  }
```


You will need to replace all your `Scaffold`s with `PlatformScaffold` and appBar with `PlatformAppBar`.

```dart
Widget build(BuildContext context) {
    return PlatformScaffold(
      appBar: PlatformAppBar(
        title: Text('Flutter Platform Widgets'),
      ),
      body: ...
    )
}
```

**Comment by erf** [comment]
That worked thanks! (not sure why you had to wrap the whole thing in a Theme, but it worked :)

I'm missing a fix for the drawer, but i guess i have to figure out that myself, since it is only supported on Material.

**Comment by fotiDim** [comment]
@erf did you find any proper way to have the drawer on iOS?

**Comment by erf** [comment]
> @erf did you find any proper way to have the drawer on iOS?

Just check in appBar.leading if platform is Cupertino then push a modal page with the same content as drawer.
