### ISSUE TITLE
AppBarTheme.elevation is not respected in PlatformAppBar

### ISSUE THREAD

**Issue by erf** [stryder-dev/flutter_platform_widgets#282]
I have set the following theme (as was explained in #279):

```
    appBarTheme: AppBarTheme(
      elevation: 0,
    ),
```

but the `elevation` is not respected in `PlatformAppBar`. Do i need to set it explicitly in `PlatformAppBar.material`?

**Comment by aqwert** [comment]
Can you show more code of where you are setting your theme

**Comment by aqwert** [comment]
I had a look and see a bug. Fix coming up

**Comment by aqwert** [comment]
Published `1.6.1` that should fix this
