### ISSUE TITLE
ListTile material splash is gone on Cupertino

### ISSUE THREAD

**Issue by erf** [stryder-dev/flutter_platform_widgets#287]
I noticed on iOS now after using the PlatformScaffold, that the ListTile no longer have the material splash effect. 

Is this how it's supposed to be?

Can i bring it back somehow?

I use ListTile for menu items among other things, and now there is no indication when pressing it.

I think ListTile would be similar as to UITableViewCell and would have an optional selection.

**Comment by aqwert** [comment]
This is the same issue with #284 with the `Material` having no effect on the CuoertinoPageScaffold. Once I move that down a level then it should work. I should get a fix out soon for that.

In the mean time you can wrap the `ListTile` with a `Material` widget

```
Material(child: ListTile(...))
```

**Comment by erf** [comment]
I made a new Flutter [issue](https://github.com/flutter/flutter/issues/81891), proposing a CupertinoTableViewCell, which we could add instead of ListTile for Cupertino. E.g. PlatformListTile.

**Comment by aqwert** [comment]
Will see where that goes. Might take some time unless someone in the community picks it up

**Comment by erf** [comment]
Yep, let's see what they say first. I'll close this now.

**Comment by erf** [comment]
There are actually work being done regarding CupertinoTableRow !

See https://github.com/flutter/flutter/issues/19228 and https://github.com/flutter/flutter/pull/78732
