### ISSUE TITLE
The PlatformAppBar.title style has changed for iOS 

### ISSUE THREAD

**Issue by erf** [stryder-dev/flutter_platform_widgets#292]
The PlatformAppBar.title style has changed for iOS in one of the last commits (maybe https://github.com/stryder-dev/flutter_platform_widgets/commit/e6b5834e6ad3e4ac45ec606b4237146d75e360a2 ? )

The title text is now smaller and more right aligned, maybe missing padding?

Screenshot:
<img width="311" alt="Screenshot 2021-05-05 at 11 51 03" src="https://user-images.githubusercontent.com/1562523/117124140-3aea4d00-ad98-11eb-8676-1ce82cffd3e2.png">

Screenshot (before):
<img width="311" alt="Screenshot 2021-05-05 at 11 52 34" src="https://user-images.githubusercontent.com/1562523/117124305-738a2680-ad98-11eb-829a-acf09f0a7b4c.png">

**Comment by aqwert** [comment]
True, down to the `Text` picking up the Material widget. Probably should be taken off at least for the title

**Comment by aqwert** [comment]
Also going to add a per `PlatformAppBar` override to turn off adding the Material widget

**Comment by erf** [comment]
Ok, great! I guess this did not make the 1.7.0 release, so look forward to the next one :)

**Comment by aqwert** [comment]
Will push 1.7.1 in a few minutes
