### ISSUE TITLE
Feature request: PlatformListTile (once CupertinoTableRow is ready)

### ISSUE THREAD

**Issue by erf** [stryder-dev/flutter_platform_widgets#296]
I'd like to see a PlatformListTile, based on ListTile for Material and CupertinoTableRow for Cupertino once ready.

I thought I'll just add this issue as a reminder to implement once the following issues are solved:

https://github.com/flutter/flutter/issues/19228
https://github.com/flutter/flutter/pull/78732

Feel free to close if pre-empt.

**Comment by aqwert** [comment]
With Flutter 3.7 there is now a Cupertino version of the LIstTile

Cupertino: https://api.flutter.dev/flutter/cupertino/CupertinoListTile-class.html
Material: https://api.flutter.dev/flutter/material/ListTile-class.html

**Comment by patricknicolosi** [comment]
I have created a pull request for add PlatformLi support  https://github.com/stryder-dev/flutter_platform_widgets/pull/385
