### ISSUE TITLE
PlatformTextFormField missing default decoration for Cupertino

### ISSUE THREAD

**Issue by itschrono** [stryder-dev/flutter_platform_widgets#300]
Hello,

Version: 1.7.1
When selected render is Cupertino this does not render as PlatformTextField because there is no decoration default value.
See: https://github.com/stryder-dev/flutter_platform_widgets/blob/2d0671ab1057a9be69e2750df7dae6dcc054bf4a/lib/src/platform_text_form_field.dart#L400
And: https://github.com/stryder-dev/flutter_platform_widgets/blob/2d0671ab1057a9be69e2750df7dae6dcc054bf4a/lib/src/platform_text_field.dart#L525

I bypassed this with a quick "dirty" fix :
```dart
final cupTextField = PlatformTextField().createCupertinoWidget(context);
PlatformTextFormField(
  cupertino: (_, __) => CupertinoTextFormFieldData(
    decoration: cupTextField.decoration,
  ),
  controller: _aliasController,
);
```

Moreover I think stuff like `_kDefaultRoundedBorderDecoration` should be public.

**Comment by aqwert** [comment]
For PlatformTextFormField, `CupertinoTextFormFieldRow.decoration` is a `BoxDecoration?` which means that if the decoration is  null then it will use whatever the library wants the decoration to be, so in effect not setting it will use the default style for `cupertino`.

For PlatformTextField, the `CupertinoTextField.decoration` is has `this.decoration = _kDefaultRoundedBorderDecoration,` so it was thought that this should be replicated. Interesting is that `decoration` does not have a null assert therefore you can set this to null to remove the border. So, in dart the `decoration` field uses default only if the field is not set which is an issue for the platform version which does set it. 

So I will add `makeCupertinoDecorationNull` on `PlatformTextField` which allows you to set it to true which will make the decoration null. 

I can make `_kDefaultRoundedBorderDecoration` be `kDefaultRoundedBorderDecoration`

**Comment by aqwert** [comment]
@RicardoRB I have been thinking about the form section concept which exists for `cupertino` but not for `material`. It is not in there at the moment
