### ISSUE TITLE
Can't find field for suffix in CupertinoTextFormFieldData

### ISSUE THREAD

**Issue by Frezyx** [stryder-dev/flutter_platform_widgets#307]
Hello ✋🏻 
I need to display the suffix widget on every platform. But there is no such field in the CupertinoTextFormFieldData class.
Example is -> [CupertinoTextField suffix](https://api.flutter.dev/flutter/cupertino/CupertinoTextField/suffix.html)

How can I make this functionality?

**Comment by aqwert** [comment]
You are confusing `PlatformTextField` and `PlatformTextFormField`. suffix exists only on the `CupertinoTextFieldData` for `PlatformTextField`. suffix does not exist for `CupertinoTextFormFieldRow`
