### ISSUE TITLE
AlertDialog button colors are not blue in default mode starting from flutter >= 2.2

### ISSUE THREAD

**Issue by andreacimino** [stryder-dev/flutter_platform_widgets#308]
After migrating to flutter 2.2, alert dialog buttons (Material Theme) have different color buttons (black) instead of blue.
When using the showDialog "native" functionality, colors are ok.
Here attached is a demo project showing the bug.

[test_bug.tar.gz](https://github.com/stryder-dev/flutter_platform_widgets/files/6536584/test_bug.tar.gz)

![bug](https://user-images.githubusercontent.com/1921442/119441149-ecd8c180-bd25-11eb-935a-1961724c3ea3.png)

Expected

<img width="150" alt="android-dialog" src="https://user-images.githubusercontent.com/1921442/119441169-f5c99300-bd25-11eb-94c0-502cd3010155.png">

**Comment by aqwert** [comment]
This is fixed in 1.9.0
