### ISSUE TITLE
Broken Images on Android

### ISSUE THREAD

**Issue by Urkman** [stryder-dev/flutter_platform_widgets#311]
I get broken Images on Android when using PlatformIcons
Seen Screenshots from iOS and Android...

Using this code:
```
Icon(
    context.platformIcons.conversationBubbleOutline,
    color: UI.colors.text(context),
    size: 18,
)
```
<img width="636" alt="Bildschirmfoto 2021-05-28 um 13 01 49" src="https://user-images.githubusercontent.com/94297/119974649-37bc3880-bfb5-11eb-9ee5-8889a14d615b.png">
<img width="493" alt="Bildschirmfoto 2021-05-28 um 13 02 20" src="https://user-images.githubusercontent.com/94297/119974659-3ab72900-bfb5-11eb-9526-8f69e092e3ad.png">

**Comment by aqwert** [comment]
That is strange considering the example icons_page renders the icons correctly. The icons are directly off the material `Icons` library. Do you have `uses-material-design: true` in your pubspec.yaml?

You can look at this as there are other possibilities: https://stackoverflow.com/questions/50786982/flutter-icons-do-not-show

**Comment by Urkman** [comment]
oh man... Yes, that was the problem :)

Thanks...
