### ISSUE TITLE
Bottom Nav Bar issues

### ISSUE THREAD

**Issue by mtgnoah** [stryder-dev/flutter_platform_widgets#314]
I just straight up can't figure out how to adapt my app for this framework and the bottom nav bar. For the different tabs can I just make those my different pages and have the tab controller click through them?? Any help is appreciated

**Comment by mtgnoah** [comment]
I want to know how I can keep the navbar persistent across all the pages I have even the ones not in the initials tab list

**Comment by aqwert** [comment]
Although I have not tried using this package, you can have a look at this article on how you could do it. Effectively you need to have a separate Navigator for each page with the Scaffold sitting above it. https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386
