### ISSUE TITLE
Error compiling example

### ISSUE THREAD

**Issue by robman70** [stryder-dev/flutter_platform_widgets#315]
Hello,
I'm new to flutter so maybe I did something wrong.

Dart SDK: 2.12.3 (stable)
Flutter 2.0.5 (stable)

When I try to compile your example project, I see an error:

Launching lib\main.dart on sdk gphone x86 in debug mode...
../lib/src/platform_app.dart:577:9: Error: No named parameter with the name 'scrollBehavior'.
        scrollBehavior: dataRouter?.scrollBehavior ?? scrollBehavior,
        ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/app.dart:217:9: Context: Found this candidate, but the arguments don't match.
  const MaterialApp.router({

        ^^^^^^^^^^^^^^^^^^
../lib/src/platform_app.dart:632:9: Error: No named parameter with the name 'scrollBehavior'.
        scrollBehavior: data?.scrollBehavior ?? scrollBehavior,

        ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/app.dart:167:9: Context: Found this candidate, but the arguments don't match.
  const MaterialApp({
        ^^^^^^^^^^^
../lib/src/platform_circluar_progress_indicator.dart:75:7: Error: No named parameter with the name 'color'.
      color: data?.color,
      ^^^^^
/C:/flutter/packages/flutter/lib/src/material/progress_indicator.dart:542:9: Context: Found this candidate, but the arguments don't match.
  const CircularProgressIndicator({
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/src/platform_nav_bar.dart:166:7: Error: No named parameter with the name 'enableFeedback'.
      enableFeedback: data?.enableFeedback,
      ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/bottom_navigation_bar.dart:257:3: Context: Found this candidate, but the arguments don't match.
  BottomNavigationBar({

  ^^^^^^^^^^^^^^^^^^^
../lib/src/platform_page.dart:128:7: Error: No named parameter with the name 'restorationId'.
      restorationId: data?.restorationId ?? restorationId,

      ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/page.dart:153:9: Context: Found this candidate, but the arguments don't match.

  const MaterialPage({
        ^^^^^^^^^^^^
../lib/src/platform_page.dart:140:7: Error: No named parameter with the name 'restorationId'.
      restorationId: data?.restorationId ?? restorationId,
      ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:419:9: Context: Found this candidate, but the arguments don't match.
  const CupertinoPage({
        ^^^^^^^^^^^^^
../lib/src/platform_text_form_field.dart:386:7: Error: No named parameter with the name 'scrollController'.
      scrollController: data?.scrollController,
      ^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_form_field.dart:135:3: Context: Found this candidate, but the arguments don't match.
  TextFormField({
  ^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by WinXaito** [comment]
Try to update flutter to `2.2.x`, i had the same problem (with `.scrollBehavior`)

**Comment by robman70** [comment]
> Try to update flutter to `2.2.x`, i had the same problem (with `.scrollBehavior`)

Thank you! I didn't realize my Flutter installation was out of date. :-(

**Comment by aqwert** [comment]
ChangeLog lists what version of Flutter is required with each version of this package. They are tightly coupled
