### ISSUE TITLE
PlatformTextFormField: setting expands is not possible

### ISSUE THREAD

**Issue by bsr203** [stryder-dev/flutter_platform_widgets#317]
`CupertinoTextFormFieldRow` has this assertion
```
       assert(
          !expands || (maxLines == null && minLines == null),
          'minLines and maxLines must be null when expands is true.',
        ),
```
which causes this error
```
minLines and maxLines must be null when expands is true.
'package:flutter/src/cupertino/text_form_field_row.dart':
Failed assertion: line 203 pos 11: '!expands || (maxLines == null && minLines == null)'
```

In [this line](https://github.com/stryder-dev/flutter_platform_widgets/blob/master/lib/src/platform_text_form_field.dart#L357),  maxLines is set to 1, if I explicitly set to null. So, looks like no way to set `expands` to `true`. May be `maxLines` cannot have default value.

**Comment by aqwert** [comment]
You are right. Downside of trying to represent a field that has a default value (1 in this case) if it is not set vs setting the field to null. Times like this I wish dart has `undefined` like javascript to represent not set vs null

**Comment by aqwert** [comment]
Will update pub.dev soon with the fix

**Comment by aqwert** [comment]
version `1.9.5` uploaded. Should fix your issue

**Comment by bsr203** [comment]
That is awesome. Thank you for all your hard work and quick response. I greatly enjoy using this package :-)
