### ISSUE TITLE
a Use with GoldenToolkit Question

### ISSUE THREAD

**Issue by fredgrott** [stryder-dev/flutter_platform_widgets#328]
So I am wrigin my first Flutter Ap dev book.

eBay's GoldenToolkit only has a materialapp wrapper.

```
WidgetWrapper materialAppWrapper({
             TargetPlatform platform = TargetPlatform.android,
             Iterable<LocalizationsDelegate<dynamic>>? localizations,
           NavigatorObserver? navigatorObserver,
             Iterable<Locale>? localeOverrides,
             ThemeData? theme,
        }) {
          return (child) => MaterialApp(
             localizationsDelegates: localizations,
              supportedLocales: localeOverrides ?? const [Locale('en')],
              theme: theme?.copyWith(platform: platform),
                 debugShowCheckedModeBanner: false,
                home: Material(child: child),
             navigatorObservers: [
          if (navigatorObserver != null) navigatorObserver,
      ],
     );
```
It would seem that I should be able to take that and come up with my own function that returns the FPW stuff before the Scaffold in the right widget tree sequence and than allow the wrapper to let developer set the target platform.

And my reasoning is that way I can run a Material look test and a Cupertino look test as part of Goldens.

Thoughts? Is this right approach?

**Comment by aqwert** [comment]
I am not familiar with that package or what you are trying to do.
