### ISSUE TITLE
The text of PlatformNavBar unselect items keep color white, without de-active with color gray !

### ISSUE THREAD

**Issue by jason19970210** [stryder-dev/flutter_platform_widgets#329]
check the images in this example !

https://www.raywenderlich.com/4968762-platform-aware-widgets-in-flutter

![](https://koenig-media.raywenderlich.com/uploads/2020/09/screen1-1-combined-transparent.png)

**Comment by aqwert** [comment]
I would need some code. That article was written by someone else
