### ISSUE TITLE
Modifying cupertino font size has no effect

### ISSUE THREAD

**Issue by svprdga** [stryder-dev/flutter_platform_widgets#330]
I'm trying to modify the font size of all the Texts in the cupertino version of my app:

```
final cupertinoTheme = CupertinoThemeData(
  textTheme: CupertinoTextThemeData(
      primaryColor: Colors.black87, textStyle: TextStyle(fontSize: 50.0)),
);
```

The code above has no effect, it doesn't matter the value I set to `fontSize`, all the Texts are rendered same as before.

**Comment by moodstubos** [comment]
Came to same issue today. 
Last code update was 3 months ago. Seems to be dead.

**Comment by aqwert** [comment]
Have you tried using the Cupertino widgets directly. There is no magic to this package other than wrapping existing material and cupertino widgets

**Comment by svprdga** [comment]
Sure, the problem is mixing cupertino and material widgets...I ended up creating my own design library, I'm closing this issue since maybe this is not a bug but a side effect.
