### ISSUE TITLE
How to implement large title navigation bar Platformscaffold

### ISSUE THREAD

**Issue by collieryroad** [stryder-dev/flutter_platform_widgets#343]
using platform scaffold - the only way i have achieved this is by using material and cupertino methods to create this - but would have a lot of repeat code i.e leading and trailing - am i missing something - would platformwidget or platformwidgetbuilder be better.

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return PlatformScaffold(
      material: (_, __) => MaterialScaffoldData(
        resizeToAvoidBottomInset: false,
        // body: const Center(
        //   child: Text('Center'),
        // ),
      ),
      cupertino: (_, __) => CupertinoPageScaffoldData(
        resizeToAvoidBottomInset: false,
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              const CupertinoSliverNavigationBar(
                largeTitle: Text('Settings'),
              )
            ];
          },
          body: const Center(
            child: Text('Center'),
          ),
        ),
      ),
      body: const Center(
        child: Text('material center Center'),
      ),
    );
  }
}

**Comment by aqwert** [comment]
If there is to much of a divergence between the Material and Cupertino designs then it may be better to use the `PlatformWidget` or `PlatfoirmWidgetBuilder` and then just design your Scaffolds for material and cupertino separately or to pull the common code out to a function used by both.
