### ISSUE TITLE
SnackBars not showing on iOS when PlatformNavBar and PlatformScaffold are used together

### ISSUE THREAD

**Issue by ercantomac** [stryder-dev/flutter_platform_widgets#356]
The issue #252 is closed saying it's not an issue of the package, but it indeed is. Normally snack bars show totally fine on iOS, but not when PlatformNavBar and PlatformScaffold are used together. (When there is no PlatformNavBar, snack bars show without any problem)

**Comment by LP0815** [comment]
Are there any news about this? (How) are you using a SnackBar in your PlatformApp, @ercantomac ?

**Comment by aqwert** [comment]
SnackBar is not a cupertino concept. If you want them in your your ios app you have to roll your own.With ScaffoldMessenger being a material widget you will need to replace that with something custom you write
