### ISSUE TITLE
How to Interchange PlatformTabScaffold with PlatformScaffold

### ISSUE THREAD

**Issue by rlfolden** [stryder-dev/flutter_platform_widgets#357]
I am building an app with PlatformTabScaffold, with a BottomNavigationBar.  

However, I need login and logout pages without any Tabs and implement those pages using PlatformScaffold.

During startup, I go to the login page and then use pushAndRemoveUntil to go to the page with the tabs, and the code works.

However, I have a logout button that logs the user out and then goes to the Login page to allow the use to login again.   

The problem is that when the login page pushes again, to the Tabbed pages, **I end up with with 2 sets of tabs along the bottom!**

This only happens on IOS, not on Android.

Is there a way to reset the environment to use either one or the other Scaffold, interchangeably?

I can provide source, but I'll have to strip my app down.  Let me know if needed.

Thanks,
Rudy

**Comment by aqwert** [comment]
Personally I would have a parent widget that would either use `PlatformScaffold` or `PlatformTabScaffold`. The issue you are seeing sounds like it is related to the way you have set things up and not specifically down to this package.
