### ISSUE TITLE
Introduce themeMode in PlatformApp

### ISSUE THREAD

**Issue by yangsfang** [stryder-dev/flutter_platform_widgets#376]
Currently in Flutter there is `themeMode` in `MaterialApp` but for `CupertinoApp` we need to set the `CupertinoThemeData` and if we need that to change at runtime we need to build a `WidgetsBindingObserver`, which clutters the code to set up `PlatformApp`. https://github.com/stryder-dev/flutter_platform_widgets/issues/202#issuecomment-705556837

Since this package is all about hiding the complexity of the differences between `MaterialApp` and `CupertinoApp` and doing the right thing depending on the runtime, is there a ways for `PlatformApp` to introduce a `themeMode` property which would simplify this setup?

Previous issues:  https://github.com/stryder-dev/flutter_platform_widgets/issues/202  https://github.com/stryder-dev/flutter_platform_widgets/issues/120

**Comment by young40** [comment]
need this too.

**Comment by aqwert** [comment]
I have added `PlatformTheme` that will update to the correct brightness based of the system theme mode changes. See versiom 3.3.1 onwards in pub.dev. For use see https://github.com/stryder-dev/flutter_platform_widgets/wiki/Theming
