### ISSUE TITLE
Bug: `iosUsesMaterialWidgets` and `legacyIosUsesMaterialWidgets` isn't used in `PlatformAlertDialog`

### ISSUE THREAD

**Issue by josxha** [stryder-dev/flutter_platform_widgets#378]
The `iosUsesMaterialWidgets` and `legacyIosUsesMaterialWidgets` attributes are currently used for `CupertinoScaffold` and `CupertinoTabScaffold`, but have no effect on `PlatformAlertDialog`. 

Since `PlatformAlertDialog` can also include material widgets, this functionality should be added here as well.

Example code:
```dart
await showPlatformDialog(context: context, builder: (context) {
  PlatformAlertDialog(
    content: ListTile(
      title: Text("This doesn't work on iOS because a Material widget is missing."),
    ),
  );
});
```

**Comment by aqwert** [comment]
Version 2.2.6 is published
