### ISSUE TITLE
Replace ToolbarOptions with contextMenuBuilder in PlatformSearchField and PlatformTextFormField

### ISSUE THREAD

**Issue by pgiokoglou** [stryder-dev/flutter_platform_widgets#380]
'ToolbarOptions' is deprecated and shouldn't be used. Use `contextMenuBuilder` instead. This feature was deprecated after v3.3.0-0.5.pre. (Documentation)  Try replacing the use of the deprecated member with the replacement.

**Comment by aqwert** [comment]
This is a Flutter 3.7 message. I have uploaded version 3.0.0 of this library that is 3.7 compatible. The deprecation is still there but there is the new property to switch over to.
