### ISSUE TITLE
About Navigation Push

### ISSUE THREAD

**Issue by programmerElephant** [stryder-dev/flutter_platform_widgets#387]
hello
 when i use your demo. when iOS push new page,i found navigation title and back button will resize with animated.
is there any setting avoid this resize animted?
thanks

https://user-images.githubusercontent.com/22141267/224279351-314957e1-09b3-4a65-83a8-e726fd7d4958.mp4

**Comment by aqwert** [comment]
It is down to this issue. See the comment. https://github.com/flutter/flutter/issues/42759#issuecomment-591087271
I will need to see what can be done with this library

**Comment by programmerElephant** [comment]
thanks
have a nice day
