### ISSUE TITLE
Material them affect Cupertino Theme look in Ios

### ISSUE THREAD

**Issue by ahmedhnewa** [stryder-dev/flutter_platform_widgets#396]
I don't want use the new PlatformTheme in 3.3, I just don't like it, I want separate themes for android and ios, after upgrade to 3.3, the functionality of change the theme mode in my app has broken, in material and cupertino property when I define different MaterialApp and CupertinoApp properties, I did define theme mode in material and custom implementation in cupertino one but it just don't work, so I have to use Platform Theme and I didn't like the way how does it work and I don't think the new way is a good idea in my opinion, is there a way to fix my issue?

I use some material widgets in cupertino app, and it look likes it take the affect of the material and cupertino theme

**Comment by aqwert** [comment]
There was a bug with the PlatformApp and pushed up 3.3.4 to fix this. You are not forced to use `PlatformTheme` and setting the theme on the `PlatformApp` should be enough as it was before `PlatformTheme` was added.

If you can provide an example that you could achieve before `PlatformTheme` was added but behaves differently then there might be an issue.
