### ISSUE TITLE
PlatformNavBar doesn't respect BottomNavigationBarType.fixed material property

### ISSUE THREAD

**Issue by royale1223** [stryder-dev/flutter_platform_widgets#397]
`PlatformNavBar `doesn't respect `BottomNavigationBarType.fixed` material property properly. As in the label size increases when a tab is selected. This is my implementation.

    return PlatformScaffold(
      backgroundColor: Colors.white,
      body: IndexedStack(
        // saves state
        index: currentIndex,
        children: screens,
      ),
      bottomNavBar: PlatformNavBar(
          currentIndex: currentIndex,
          itemChanged: (index) => setState(() => currentIndex = index),
          material: (context, platform) {
            return MaterialNavBarData(
              type: BottomNavigationBarType.fixed, 
            );
          },

Currently using   `flutter_platform_widgets: ^3.2.0`

**Comment by aqwert** [comment]
From my testing this is flutter behaviour. Using just material widgets also demonstrates this

```
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: const Text('App bar')),
      body: IndexedStack(
        // saves state
        index: currentIndex,
        children: const [
          Center(
            child: Text('First'),
          ),
          Center(
            child: Text('Second'),
          ),
        ],
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: currentIndex,
        onTap: (index) => setState(() => currentIndex = index),
        type: BottomNavigationBarType.fixed,
        items: const [
          BottomNavigationBarItem(
              icon: Icon(Icons.heart_broken_outlined), label: 'Heart'),
          BottomNavigationBarItem(
              icon: Icon(Icons.local_airport), label: 'Airport'),
        ],
      ),
    );
  }
}
```
