### ISSUE TITLE
Dark mode does not work for Flutter `3.10`

### ISSUE THREAD

**Issue by Myzel394** [stryder-dev/flutter_platform_widgets#402]
Dark mode is not properly recognized when using version `^3.0.0` of this package and Flutter `3.10` (when using `darkTheme` and `theme`). Related to #401

**Comment by aqwert** [comment]
Can you provide an example code that replicates this. The example project seems to work ok but there might be something else going on

**Comment by aqwert** [comment]
I have published v3.3.4 that should fix this for you
