### ISSUE TITLE
CupertinoButton has no ability to set border

### ISSUE THREAD

**Issue by danielnordh** [stryder-dev/flutter_platform_widgets#412]
I'm trying to create platform equivalents for an outline button.
On Android it's straightforward with... OutlinedButton, but on iOS it doesn't seem possible with CupertinoButton?

If I use OutlinedButton on iOS, the tap behaviour is different and looks jarring next to a CupertinoButton.
Am I missing something, or is this not possible.

**Comment by aqwert** [comment]
You might want to raise a ticket with https://github.com/flutter/flutter/issues as this library only wraps exiting material and cupertino widgets provided but flutter itself. If you want to create your own cupertino like button, then you can use `PlatformWidget` to return the material or your new widget depending on the platform.
