### ISSUE TITLE
Material 3 NavigationBar

### ISSUE THREAD

**Issue by alxlion** [stryder-dev/flutter_platform_widgets#421]
The PlatformAppBar uses the BottomNavigationBar from Material 2. 

But If you use Material 3 in the Flutter app (by setting `useMaterial3: true`), [NavigationBar](https://api.flutter.dev/flutter/material/NavigationBar-class.html) should be used.

**Comment by aqwert** [comment]
I have put that in and it is up `4.0.0-beta.2.`
