### ISSUE TITLE
How can I apply decoration to PlatformTextFormField ?

### ISSUE THREAD

**Issue by developer82** [stryder-dev/flutter_platform_widgets#436]
I see that most of the TextFormField properties I expect to find are there, but decoration isn't, but I do need to apply my own decoration.

**Comment by bookshiyi** [comment]
May be you could try it like this:

``` dart
PlatformTextFormField(
    hintText: 'hint',
    validator: (value) =>
        (value?.length ?? 0) < 3 ? 'Not enough' : null,
    autovalidateMode: AutovalidateMode.always,
+   material: (_, __) => MaterialTextFormFieldData(
+     decoration: 
+     ...
+   ),
+   cupertino: (_, __) => CupertinoTextFormFieldData(
+     decoration: 
+     ...
+   ),
  ),
```

**Comment by aqwert** [comment]
As @bookshiyi states you need to use the `material` and `cupertino` fields since they use different types. `InputDecoration` for material and `BoxDecoration` for cupertino
