### ISSUE TITLE
Is the project alive??

### ISSUE THREAD

**Issue by freshtechtips** [stryder-dev/flutter_platform_widgets#438]
I hope this message finds you well, it has been a few months and no one has reacted to this project

1. no accepting pull request
2. no more new issues
3. no commits
4. no updates

I wonder what happened??

**Comment by code-gezellig** [comment]
So a pity that we don't have any feedback from the developers. If they can't develop the project anymore, probably we need to arrange a new pipeline in a forked repository..

**Comment by freshtechtips** [comment]
> So a pity that we don't have any feedback from the developers. If they can't develop the project anymore, probably we need to arrange a new pipeline in a forked repository..

I was about to the moment I sent a pull reques

But unfortunately for now I have many things in my to-do list and so I couldn't but if the project is really dead then we all have to make it live again.

**Comment by aqwert** [comment]
Sorry for this. I have been swamped with work and kids and being away for a time. I will work through updating the package and go through PRs in the next few days. I will release a flutter 3.13 compatible version probably just in time for flutter to release 3.16 (or whatever it is going to be)

**Comment by freshtechtips** [comment]
> Sorry for this. I have been swamped with work and kids and being away for a time. I will work through updating the package and go through PRs in the next few days. I will release a flutter 3.13 compatible version probably just in time for flutter to release 3.16 (or whatever it is going to be)

Thank you for your time and efforts to the open sourcd community as well as your time to the kids.

**Comment by code-gezellig** [comment]
> Sorry for this. I have been swamped with work and kids and being away for a time. I will work through updating the package and go through PRs in the next few days. I will release a flutter 3.13 compatible version probably just in time for flutter to release 3.16 (or whatever it is going to be)

Thank you for the reply and magaing everything! I hope you are doing well :-)
