### ISSUE TITLE
Bug: Compiling android version - argument type 'bool?' can't be assigned to the parameter type 'bool'

### ISSUE THREAD

**Issue by typexy** [stryder-dev/flutter_platform_widgets#440]
used version is the latest one - 5.0.0

I do receive "argument type 'bool?' can't be assigned to the parameter type 'bool'"
```

"Install Android SDK Platform 34 (revision: 2)" finished.
../../.pub-cache/hosted/pub.dev/flutter_platform_widgets-5.0.0/lib/src/platform_text_field.dart:583:30: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
      enabled: data?.enabled ?? enabled,
                             ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/builder/programs/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/builder/programs/flutter/bin/flutter'' finished with non-zero exit value 1

```

What could be the issue?

**Comment by akshay-v9** [comment]
Please help with this asap

**Comment by vadrian89** [comment]
Hello, surprisingly, I have this error on codemagic but not on any of my local machines (neither Linux/Android, or macOS/iOS).
Happening with Flutter 3.13.8

**Comment by vadrian89** [comment]
What Flutter version are you using? Codemagic seems to be installing 3.16, so most likely, that's why my build fails. I am using 3.18.3 on my local machines and don't have this issue.
Run a `flutter doctor -v` and post it here.

**Comment by Aulig** [comment]
![grafik](https://github.com/stryder-dev/flutter_platform_widgets/assets/32148066/67007df3-4d78-4ce7-b956-c866cb963785)

Of course I'm also looking forward to Flutter 3.16 support, but problems are to be expected when it is not officially supported.
