### ISSUE TITLE
How to work with GetX library together?

### ISSUE THREAD

**Issue by wzhou-grid** [stryder-dev/flutter_platform_widgets#448]
Could anyone demo how to set up the flutter_platform_widgets along with GetX? Thanks.

**Comment by aqwert** [comment]
Unfortunately the issue with GetX is that it used a MaterialApp under the hood and is very opinionated package. You might be able to get it to work by just using `PlatformProvider` and just individual widgets on each page but for iOS the behaviour might be off if it does not use the `CupertinoApp` under the hood. I suggest asking the question on that repo or if someone else has dealt with this
