### ISSUE TITLE
Where are the Docs?

### ISSUE THREAD

**Issue by PatrickLumenus** [stryder-dev/flutter_platform_widgets#70]
This library looks great. I am wondering where the docs are for using this library? Or, when we can expect them.

**Comment by aqwert** [comment]
it is on the todo list, no eta. The fields are identical to the underlying material and cupertino widgets. Just need to spend time to bring the documentation across

**Comment by PatrickLumenus** [comment]
Okay. Looks good. Thanks. I guess I'll do the best I can with it for now. lol.

**Comment by aqwert** [comment]
Documentation is being tracked at #271
